### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by EYHN** [EYHN/space-thumbnails#1]
This project is in the very early stages of development, and here are the goals to be completed in the near future。

## Optimization

* [ ] Using process isolation + IPC to prevent the errors that can cause Windows Explorer to crash or get stuck.
* [ ] Caching rendering contexts to improve rendering speed.

## Support Formats

* [ ] Blender File (.blend)
* [ ] STEP File (.stp/.step)

**Comment by jgod** [comment]
Blender 😋

**Comment by boromyr** [comment]
Are there any updates on support for .step files?

**Comment by CiberNin** [comment]
> Are there any updates on support for .step files?

I too would desire this feature.
